//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnModelValidate.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tStudent
    {
        [DisplayName("學號")]
        [Required(ErrorMessage = "NOT NULL")]
        [StringLength(7,ErrorMessage="LENGTH=7")]
        public string fStuId { get; set; }
        [DisplayName("姓名")]
        [Required(ErrorMessage ="NOT NULL")]
        public string fName { get; set; }
        [DisplayName("信箱")]
        [EmailAddress(ErrorMessage = "format")]
        public string fEmail { get; set; }
        [DisplayName("成績")]
        [Range(0,100,ErrorMessage = "1-100")]

        public Nullable<int> fScore { get; set; }
    }
}
